---
name: "Profilarr v1"
version: "0.1.12"
slug: "profilarr-v1"
description: "Profile management for *arr applications (Sonarr, Radarr, etc.)"
arch:
  - amd64
  - aarch64
url: https://github.com/Dictionarry-Hub/profilarr
image: "ghcr.io/rigerc/ha-addons-profilarr-v1-{arch}"
startup: services
boot: manual
init: false
ingress: true
ingress_port: 6099
panel_icon: mdi:file-document-multiple
map:
  - addon_config:rw
  - share:rw
options:
  log_level: info
  tz: UTC
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  tz: str
