---
name: "Profilarr"
version: "1.0.0"
slug: "profilarr"
description: "Profile management for *arr applications (Sonarr, Radarr, Lidarr)"
arch:
  - aarch64
  - amd64
  - armv7
url: https://github.com/Sonarr/Sonarr
startup: application
boot: manual
ingress: true
ingress_port: 8099
panel_icon: mdi:file-document-multiple
map:
  - addon_config:rw
  - share:rw
options:
  log_level: info
  tz: UTC
  git_user_name: "Profilarr"
  git_user_email: "profilarr@dictionarry.com"
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  tz: str
  git_user_name: str
  git_user_email: str
