---
name: "Profilarr"
version: "0.1.5"
slug: "profilarr"
description: "Profile management for *arr applications"
arch:
  - aarch64
  - amd64
image: "ghcr.io/rigerc/ha-addons-profilarr-v1-{arch}"
url: https://github.com/Sonarr/Sonarr
boot: manual
ingress: true
ingress_port: 6099
panel_icon: mdi:file-document-multiple
map:
  - addon_config:rw
  - share:rw
options:
  log_level: info
  tz: UTC
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  tz: str
